import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import static java.lang.Thread.sleep;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jorge
 */
public class frmInicio extends javax.swing.JFrame {
//int minutos=0;
//int segundos=0;
    public Clip clip;
    public String ruta = "/Audio/";
    private String Cedula = "";
    int miliseg=0;
    int seg=0;
    int min=0;
    int hora=0;
    boolean estado=true;


    

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("Carrera");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblLinea = new javax.swing.JLabel();
        lblauto1 = new javax.swing.JLabel();
        lblauto2 = new javax.swing.JLabel();
        lblauto3 = new javax.swing.JLabel();
        lblauto4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblBandera = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtR = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCrono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLinea.setBackground(new java.awt.Color(204, 204, 204));
        lblLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fin.png"))); // NOI18N
        jPanel1.add(lblLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 90, 340));

        lblauto1.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblauto1.setForeground(new java.awt.Color(255, 255, 0));
        lblauto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras (1).png"))); // NOI18N
        jPanel1.add(lblauto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 45));

        lblauto2.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblauto2.setForeground(new java.awt.Color(51, 255, 51));
        lblauto2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras (2).png"))); // NOI18N
        jPanel1.add(lblauto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 45));

        lblauto3.setBackground(new java.awt.Color(0, 0, 255));
        lblauto3.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblauto3.setForeground(new java.awt.Color(0, 0, 255));
        lblauto3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras (3).png"))); // NOI18N
        jPanel1.add(lblauto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 45));

        lblauto4.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        lblauto4.setForeground(new java.awt.Color(255, 0, 0));
        lblauto4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/coche-de-carreras4.png"))); // NOI18N
        jPanel1.add(lblauto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 45));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("START");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 60, 30));

        lblBandera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bandera.png"))); // NOI18N
        jPanel1.add(lblBandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, 39));

        jButton3.setText("PARAR");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 60, 30));

        txtR.setEditable(false);
        txtR.setColumns(20);
        txtR.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        txtR.setRows(5);
        txtR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane1.setViewportView(txtR);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 170, 220));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("NEW");
        jButton2.setToolTipText("n");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 60, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1 (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 610, 170));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1 (1).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 170));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1 (1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 170));
        jPanel1.add(txtCrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 160, 40));

        jLabel6.setText("Tiempo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));

        jButton4.setText("Audio");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 899, 410));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/multi.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 310));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calle.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 660));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmInicio.txtR.setText("->");
        carrera.iniciar();
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
        
        ////////////////////////////////////////////////////////////
      
       estado=false;
       Thread hilo = new Thread(){
       public void run(){
           while(true){
            if (estado==false) {  
             try{   
            sleep(1);
            if(miliseg>=100){
                miliseg=0;
                seg++;
            }
            if(seg>=60){
                miliseg=0;
                seg=0;
                min++;
            }
            if(min>=60){
                miliseg=0;
                seg=0;
                min=0;
                hora++;
                
            }
            txtCrono.setText(hora +" :"+min+" :"+seg+" :" +miliseg+"");
            //txtCrono.setText(""+miliseg);
            miliseg++;
           }catch(Exception e){
                 
             }
           }else{
                break;
            }
         } 
       }
       };
       hilo.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        carrera.reiniciar();
        lblauto1.setLocation(carrera.losautos[0].getCoorX(), carrera.losautos[0].getCoorY());
        lblauto2.setLocation(carrera.losautos[1].getCoorX(), carrera.losautos[1].getCoorY());
        lblauto3.setLocation(carrera.losautos[2].getCoorX(), carrera.losautos[2].getCoorY());
        lblauto4.setLocation(carrera.losautos[3].getCoorX(), carrera.losautos[3].getCoorY());
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jButton2.setEnabled(false);
        carrera.registrarAutos();
        lblauto1.setText(carrera.losautos[0].getNombre());
        lblauto2.setText(carrera.losautos[1].getNombre());
        lblauto3.setText(carrera.losautos[2].getNombre());
        lblauto4.setText(carrera.losautos[3].getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        estado=true;
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
sonido("multitud");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
private void sonido(String archivo) {
try {
            clip = AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav")));
            clip.start();
        } catch (Exception e) {

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblBandera;
    public static javax.swing.JLabel lblLinea;
    public static javax.swing.JLabel lblauto1;
    public static javax.swing.JLabel lblauto2;
    public static javax.swing.JLabel lblauto3;
    public static javax.swing.JLabel lblauto4;
    private javax.swing.JTextField txtCrono;
    public static javax.swing.JTextArea txtR;
    // End of variables declaration//GEN-END:variables
}
